FARM_COUNTER = 2
FARM_ONE_POSITION = 'farm1_pos1'
FARM_ONE_WATERING_BONUS = 10
FARM_TWO_POSITION = 'farm1_pos3'
FARM_TWO_WATERING_BONUS = 10
FARM_THREE_POSITION = ''
FARM_THREE_WATERING_BONUS = ''
COOP_COUNTER = 1
COOP_POSITION = ''

